### Get all location
GET http://localhost:3000/locations
### Get a location by City
# GET http://localhost:3000/locations/Monrovia


### Get a location by ID
GET http://localhost:3000/locations/683cf935487783d0b5144b76


### Create a new location
POST http://localhost:3000/locations
Content-Type: application/json

{
  "Country": "Liberia",
  "City": "Monrovia"
}


### Update a location by ID
PUT http://localhost:3000/locations/683cf935487783d0b5144b76
Content-Type: application/json

{
  "Country": "USA",
  "City": "Paynesville"
}


### Delete a location by ID
DELETE http://localhost:3000/locations
